=== harinyadevi/Net_centric_programming/form1.dtd
<!DOCTYPE form1
[
<!ELEMENT form1 (fname, lname, org, tit, rts, tel, email)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT org (#PCDATA)>
<!ELEMENT tit (#PCDATA)>
<!ELEMENT rts (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA) #REQUIRED>
]>

=== harinyadevi/Net_centric_programming/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "form1.dtd">
<form1>
<fname>Aravindh</fname>
<lname>Venkat</lname>
<org>Amrita</org>
<tit>Prof</tit>
<rts>Prof</rts>
<tel>123345</tel>
<email>abc@gmail.com</email>
</form1>
